package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-i586-cygwin/jdk8u191/11896/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Saturday, October 6, 2018 8:35:30 AM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
	 * The value representing LIFESPAN_POLICY_ID.
	 */
  public static final int value = (int)(17L);
}
